excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - gem_dependencies
identifier_name:
  allowed_symbols: "_"
disabled_rules:
  - variable_name
  - line_length
  - trailing_whitespace
  - cyclomatic_complexity
  - type_body_length
line_length:
  ignores_comments: true
  ignoresInterpolatedStrings: true
line_length: 280
function_body_length:
  - 300 # warning
  - 400 # error
