# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cocoapods' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cocoapods
  pod 'Alamofire', '~> 5.0.0-rc.2'
  pod 'KeychainAccess', '~> 3.2.0'
  pod 'lottie-ios', '~> 3.1.3'
  pod 'RxSwift', '~> 5.0.0'
  pod 'RxCocoa', '~> 5.0.0'
  pod 'SwiftLint', '~> 0.35.0'

end
